FROM node:21-alpine

WORKDIR /usr/app

COPY package*.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/local/myapp/node_modules/.bin:$PATH

WORKDIR /usr/app/dev
COPY tsconfig.json ./

COPY src ./src
COPY .env ./

EXPOSE 8080

CMD [ "npm", "start" ]